import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useState } from 'react'
import Image from "next/image"
import logo from '../assets/logo.png'
//import { CircleLoader  } from 'react-spinners'
//import {CSSProperties } from 'react'
import Modal from 'react-modal'
//import { css } from '@emotion/react'
import {ProgressBar} from "react-loader-spinner";

const style = {
  wrapper: `text-white h-96 w-72 rounded-lg flex flex-col justify-center items-center`,
  title: `font-semibold text-xl mb-12 text-center mt-3 fw-bold`,
  spin: `justify-center items-center text-center`,
}


Modal.setAppElement('#react-modals')

const customStyles = {
  content: {
    top: '50%',
    left: '50%',
    height: '25vh',
    width: '25vh',
    right: 'auto',
    bottom: 'auto',
    transform: 'translate(-50%, -50%)',
    backgroundColor: '#0a0b0d',
    padding: 0,
    border: 'solid 2px #51E5FF',
    overflow: 'hidden',
  },
  overlay: {
    backgroundColor: 'rgba(10, 11, 13, 0.75)',
    overflow: 'auto',
  },
}

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [downloads, setDownloads] = useState<string>('')
  const [input, setInput] = useState<string>('')
  const [search, setSearch] = useState<boolean>(false)
  const [modal, setModal] = useState<boolean>(false)

  const getDownloads = async () => {
    //change this when server deployed
    //start modal
    setModal(true)
    const res = await fetch('http://localhost:3000/api/getDownloads', {
      method: 'POST',
      body: JSON.stringify({input})
    })
    const { downloads } = await res.json()
    //closemodal
    setModal(false)
    setDownloads(downloads)
    setSearch(true)
  } 

  function clear() {
    if (search) {
      setSearch(false)
      setInput('')
    }
  }

  return (
    <>
      <Head >
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container justify-content-center text-center mt-3">
        <Image src={logo} alt='site_logo' className='site_logo'/>
      </div>

      {modal ? (
          <Modal isOpen={modal} style={customStyles} >
            <div className={style.wrapper}>
              <div className={style.title}>Loading</div>
              <div className={style.spin}>
                <ProgressBar
                  height="100"
                  width="100"
                  ariaLabel="progress-bar-loading"
                  wrapperStyle={{}}
                  wrapperClass="progress-bar-wrapper"
                  borderColor = '#003366 '
                  barColor = '#51E5FF'
                />
              </div>
            </div>
          </Modal>
      ): null}
      
      <div id="react-modals" className='container w-50 border border-5 rounded rounded-4 border-dark main'>
        <div className='mt-4 container w-50 p-5 vstack gap-2 col-md-5 mx-auto'>
          <h3 className='justify-content-center text-center text-white'>Airline Saftey Rating Search</h3>
          <input value={input} onClick={() => clear()}  onChange={(e) => setInput(e.target.value)} type='text' 
          placeholder='Enter Airline Name' className='mt-2'/>
          <button onClick={getDownloads}  type='button' className='btn btn-primary mt-2'>Generate</button>
          {search ? (
            <p className='fw-bold text-white justify-content-center text-center mt-2'>
              {input.toUpperCase()} is Rated {downloads} For Saftey</p>
          ): null}
        </div>
      </div>

      <div className="navbar fixed-bottom d-inline-flex justify-content-center align-content-center">
        <p className='text-white opacity-50 text-center' > Developed by Nikhil Naik, WaveFlightSimulation © All Rights Reserved.</p>
      </div>
    </>
  )
}
